# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# Comment this
version: 2.1
parameters:
  print-hello:
    type: boolean
    default: false
  config:
    type: string
    default: 'hi'
  dt:
    type: enum    
    default: "apk"
    enum: ["apk", "bundle"]
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    working_directory: ~/project
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run: |
          export configFolder="$(echo "<<pipeline.parameters.config>>" | sed 's/.*/\u&/')"
          echo "Hello there" > $configFolder
          cat $configFolder
          #java --version
          # sudo apt update && sudo apt install -y binfmt-support qemu qemu-user-static apksigner
          # lscpu
          # sudo find / -name "build-tools"
          # ls /home/circleci/android-sdk/build-tools/33.0.0/
          # sudo find / -name "apksigner"
          # printenv
          # apksigner --help
          #$ANDROID_SDK_ROOT/build-tools/33.0.0/apksigner --help
      - run:
          name: "Write hello"
          command: echo "Hello" > file.txt
      - run: echo ${MY_ENV_VAR}
      - when:
          condition:
            equal: [true, << pipeline.parameters.print-hello>>]
          steps:
          - run:
              name: "Print Hellow"
              command: cat file.txt

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          post-steps:
            - run: |
                STATUS=$(curl "https://circleci.com/api/v2/pipeline/$PIPELINE/workflow?circle-token=$CIRCLE_TOKEN" | jq -r '.items[].status')
                echo "Build (<< pipeline.number >>) $STATUS for $CIRCLE_BRANCH. Build details are available at $CIRCLE_BUILD_URL"
